insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (1, 'Riffwire', '574-970-9740', 'gworner0@discovery.com', '1 Fieldstone Parkway');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (2, 'Realbuzz', '646-645-1286', 'ritzhaiek1@ow.ly', '83360 Red Cloud Drive');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (3, 'Browseblab', '420-249-3401', 'wdebeneditti2@goo.ne.jp', '204 Forest Run Street');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (4, 'Jabberstorm', '155-905-9197', 'mlunbech3@icq.com', '7313 Sutherland Way');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (5, 'Skajo', '804-716-2345', 'jfavel4@yahoo.co.jp', '5 Mariners Cove Point');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (6, 'Realbuzz', '762-898-2866', 'lfley5@bigcartel.com', '7909 Pearson Place');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (7, 'Skimia', '932-560-0614', 'eridley6@patch.com', '1163 Oak Valley Parkway');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (8, 'Myworks', '381-661-2529', 'hmohun7@google.com', '74 Cascade Junction');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (9, 'Oozz', '246-955-7256', 'cfaull8@prweb.com', '5 Blue Bill Park Parkway');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (10, 'Browsebug', '626-937-3266', 'hcarren9@ibm.com', '68031 Spaight Point');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (11, 'Brainlounge', '146-381-3656', 'aflickera@businesswire.com', '63457 Bashford Center');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (12, 'Trilith', '646-872-1731', 'wsommerledb@sbwire.com', '2216 Magdeline Junction');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (13, 'Devify', '638-745-7058', 'apolgreenc@marketwatch.com', '3 Surrey Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (14, 'Meevee', '607-441-9760', 'rdionsettod@canalblog.com', '4377 Grim Center');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (15, 'Pixonyx', '927-259-7852', 'dfantine@wsj.com', '92 Sutherland Hill');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (16, 'Mita', '588-578-4682', 'nrailtonf@theatlantic.com', '2638 Graedel Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (17, 'Voolith', '511-241-4710', 'mpeperellg@hc360.com', '01222 Cottonwood Plaza');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (18, 'Linklinks', '571-991-2805', 'floggh@qq.com', '2476 Columbus Street');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (19, 'Oyoyo', '291-887-1981', 'cmurrilli@jalbum.net', '9 Ramsey Plaza');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (20, 'Livepath', '562-930-1929', 'yhostenj@gizmodo.com', '4 Sauthoff Place');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (21, 'Tazz', '718-324-3291', 'gwaltersk@pbs.org', '653 Sunnyside Alley');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (22, 'Gigaclub', '858-165-6862', 'vrylesl@ocn.ne.jp', '242 Chive Street');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (23, 'Voolia', '844-414-8016', 'spetraschm@admin.ch', '98017 Florence Drive');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (24, 'Npath', '451-425-3929', 'drevittn@miitbeian.gov.cn', '64537 Roth Court');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (25, 'Trudoo', '938-706-6153', 'cbillso@dropbox.com', '68491 Dovetail Circle');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (26, 'Topicware', '879-121-7401', 'koliveyp@uol.com.br', '2949 Hermina Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (27, 'Photofeed', '897-662-5412', 'aleyburnq@stanford.edu', '31894 Talmadge Drive');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (28, 'Tagopia', '962-683-1877', 'rtuttonr@webeden.co.uk', '79 Vahlen Parkway');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (29, 'Quire', '534-103-7105', 'nnoonans@phpbb.com', '52315 Forest Crossing');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (30, 'Livepath', '220-366-4860', 'acluleyt@homestead.com', '5124 Crownhardt Point');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (31, 'Rhybox', '251-878-1358', 'ntollemacheu@1und1.de', '79 Loeprich Plaza');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (32, 'Mybuzz', '891-391-1516', 'rjoanaudv@google.com.hk', '0 Lakewood Gardens Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (33, 'Oyonder', '636-247-1321', 'wzanassiw@sphinn.com', '318 Sunnyside Drive');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (34, 'Eire', '620-856-9377', 'lpasterfieldx@trellian.com', '449 Blaine Park');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (35, 'Katz', '732-431-1064', 'censleyy@ameblo.jp', '5364 Village Green Plaza');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (36, 'Avavee', '211-999-6914', 'bdilliwayz@un.org', '20 Miller Alley');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (37, 'Youspan', '765-360-5947', 'crevitt10@zimbio.com', '367 Artisan Alley');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (38, 'Latz', '944-131-0684', 'teverist11@networksolutions.com', '62 Express Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (39, 'Pixonyx', '847-821-6630', 'vtraher12@illinois.edu', '276 Hovde Trail');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (40, 'Zoonoodle', '184-188-3941', 'cdomb13@dedecms.com', '79216 Old Gate Court');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (41, 'Divavu', '607-421-2509', 'sbehling14@latimes.com', '620 Del Mar Trail');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (42, 'Voonyx', '402-313-6693', 'htraynor15@livejournal.com', '432 Jana Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (43, 'Skipfire', '258-613-7245', 'jtalby16@walmart.com', '69786 Hagan Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (44, 'Linkbuzz', '948-459-0093', 'cbaistow17@twitpic.com', '0657 Duke Hill');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (45, 'Jabbercube', '688-704-0434', 'ifabry18@jugem.jp', '4119 Katie Way');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (46, 'Brightbean', '425-699-7423', 'balkin19@mit.edu', '428 Grayhawk Lane');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (47, 'Tanoodle', '217-497-2545', 'massiratti1a@cornell.edu', '676 Troy Court');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (48, 'Buzzster', '313-536-4679', 'emacgee1b@domainmarket.com', '8 Sullivan Place');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (49, 'Ainyx', '598-678-8519', 'mkincla1c@pbs.org', '99531 Sachtjen Way');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (50, 'Midel', '671-416-0317', 'mfries1d@patch.com', '18064 Heath Park');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (51, 'Topiclounge', '571-429-9470', 'bgranville1e@omniture.com', '256 Longview Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (52, 'Browsezoom', '518-919-2347', 'jbiesterfeld1f@exblog.jp', '911 Dawn Hill');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (53, 'Feedmix', '612-769-1865', 'lmoryson1g@delicious.com', '69319 1st Trail');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (54, 'Quimm', '643-405-3326', 'jbigley1h@edublogs.org', '21544 Algoma Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (55, 'Tazz', '661-852-6402', 'twaltering1i@wired.com', '393 Milwaukee Court');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (56, 'Realmix', '428-552-7843', 'mmatushevich1j@youtu.be', '1727 Kenwood Street');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (57, 'Realcube', '213-701-8619', 'iglencrosche1k@soundcloud.com', '4941 Hermina Court');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (58, 'Gabspot', '977-444-0036', 'hketts1l@chronoengine.com', '60 Fairfield Street');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (59, 'Devpulse', '957-760-9774', 'elevine1m@newsvine.com', '2 Oriole Terrace');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (60, 'Babblestorm', '168-735-0944', 'mstackbridge1n@thetimes.co.uk', '699 Rutledge Park');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (61, 'Zava', '164-247-9909', 'kgritland1o@joomla.org', '74 Shopko Point');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (62, 'Mynte', '357-768-9072', 'dshowers1p@goo.gl', '4850 Ronald Regan Terrace');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (63, 'Topdrive', '130-338-6834', 'jarnowitz1q@illinois.edu', '570 Ridgeway Hill');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (64, 'Riffpath', '834-756-8049', 'scosby1r@marriott.com', '2 Kropf Junction');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (65, 'Ailane', '666-373-0487', 'ksutworth1s@bing.com', '6 Gateway Place');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (66, 'Linktype', '678-510-0519', 'btessier1t@liveinternet.ru', '917 Namekagon Street');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (67, 'Trudeo', '386-910-0783', 'gisaacson1u@amazonaws.com', '91 Butternut Way');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (68, 'Agimba', '458-269-9334', 'smunslow1v@livejournal.com', '1338 Talisman Lane');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (69, 'Livetube', '367-526-5833', 'fhumerstone1w@ehow.com', '4410 Derek Drive');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (70, 'Mynte', '461-845-3020', 'fgrosier1x@msu.edu', '6787 Spaight Crossing');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (71, 'Youbridge', '384-194-0032', 'tiacovucci1y@cornell.edu', '4337 Truax Drive');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (72, 'Feednation', '563-434-9114', 'troadknight1z@free.fr', '4496 Kropf Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (73, 'Eidel', '189-314-5273', 'lgooderidge20@artisteer.com', '6640 Riverside Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (74, 'Flashspan', '490-629-6219', 'rcruse21@businessweek.com', '147 Carpenter Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (75, 'Yadel', '576-241-5974', 'khaffner22@wikispaces.com', '421 Hudson Alley');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (76, 'Quatz', '113-853-5917', 'mderry23@1und1.de', '6521 Mesta Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (77, 'Photojam', '538-312-7408', 'asolan24@nature.com', '5 Grim Junction');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (78, 'Rhynyx', '651-291-0341', 'rkenny25@technorati.com', '0452 Heath Alley');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (79, 'Einti', '492-384-9374', 'eelington26@ovh.net', '12 Nevada Way');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (80, 'Oba', '942-952-8802', 'bjugging27@over-blog.com', '33 Waxwing Trail');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (81, 'Skalith', '394-515-0276', 'qpolding28@macromedia.com', '73 Shasta Circle');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (82, 'Blogtags', '896-195-3521', 'jcutmore29@irs.gov', '6 Lotheville Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (83, 'Shufflester', '847-855-5184', 'fmarshman2a@globo.com', '667 Gina Drive');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (84, 'Shufflebeat', '842-657-8913', 'mdilloway2b@bloomberg.com', '0716 Corscot Junction');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (85, 'Blogspan', '770-708-5431', 'ghatchett2c@skype.com', '79 Farmco Park');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (86, 'Linktype', '281-383-0071', 'hobradden2d@hao123.com', '24 Mallard Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (87, 'Realmix', '181-306-7629', 'fboar2e@cyberchimps.com', '4118 Old Shore Circle');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (88, 'Riffpath', '893-288-3927', 'aliveing2f@vkontakte.ru', '2 Logan Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (89, 'Reallinks', '557-674-6443', 'nstarkey2g@weebly.com', '9918 Haas Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (90, 'Pixope', '181-276-8739', 'fjaegar2h@naver.com', '321 John Wall Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (91, 'Skyba', '710-376-8228', 'apietron2i@surveymonkey.com', '9735 Wayridge Parkway');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (92, 'Layo', '734-594-2506', 'omerwede2j@dailymotion.com', '7 Tomscot Terrace');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (93, 'Zazio', '485-671-9159', 'fcassy2k@nih.gov', '815 Bluejay Point');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (94, 'Brainlounge', '913-283-0770', 'hbroker2l@timesonline.co.uk', '02470 Barnett Road');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (95, 'Zoovu', '861-207-1488', 'dbelbin2m@cloudflare.com', '92855 Lerdahl Plaza');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (96, 'Rhyzio', '834-381-9874', 'jlightbody2n@marriott.com', '36 Acker Park');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (97, 'Kwilith', '967-923-4755', 'bhuffadine2o@drupal.org', '66099 Hanson Pass');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (98, 'Mita', '407-666-6968', 'awadman2p@angelfire.com', '4672 Sachtjen Junction');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (99, 'Jatri', '392-889-5773', 'gcurley2q@google.com.hk', '1 Maywood Way');
insert into Company (CompanyID, CompanyName, CompanyPhone, CompanyEmail, CompanyAddress) values (100, 'Roombo', '349-114-8643', 'plackham2r@bloglines.com', '733 Mayer Street');
