insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (1, 'Oatmeal cookies', 'dry food', 13, 91, 65);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (2, 'Clams', 'portion options: small or large', 2, 25, 45);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (3, 'Oatmeal cookies', 'dry food', 5, 35, 71);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (4, 'Clams', 'portion options: small or large', 3, 52, 58);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (5, 'Oatmeal cookies', 'dry food', 2, 78, 47);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (6, 'Still water', 'refreshing drink', 12, 31, 40);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (7, 'Sparkling water', 'The water contains a lot of magnesium', 5, 99, 46);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (8, 'Octopus', 'options: small or large', 8, 63, 55);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (9, 'Instant coffee', 'caffeine drink', 1, 10, 86);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (10, 'Clams', 'portion options: small or large', 2, 86, 40);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (11, 'Clams', 'portion options: small or large', 6, 33, 16);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (12, 'Oatmeal cookies', 'dry food', 10, 63, 41);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (13, 'Still water', 'refreshing drink', 5, 52, 16);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (14, 'Still water', 'refreshing drink', 12, 43, 54);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (15, 'Still water', 'refreshing drink', 7, 100, 93);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (16, 'Still water', 'refreshing drink', 11, 56, 49);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (17, 'Instant coffee', 'caffeine drink', 7, 33, 69);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (18, 'Still water', 'refreshing drink', 8, 17, 1);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (19, 'Clams', 'portion options: small or large', 13, 47, 77);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (20, 'Sparkling water', 'The water contains a lot of magnesium', 11, 15, 5);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (21, 'Clams', 'portion options: small or large', 11, 69, 16);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (22, 'Octopus', 'options: small or large', 10, 89, 93);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (23, 'Sparkling water', 'The water contains a lot of magnesium', 1, 2, 71);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (24, 'Oatmeal cookies', 'dry food', 7, 10, 32);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (25, 'Octopus', 'options: small or large', 10, 12, 64);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (26, 'Still water', 'refreshing drink', 13, 76, 48);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (27, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 10, 24, 94);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (28, 'Oatmeal cookies', 'dry food', 14, 12, 64);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (29, 'Instant coffee', 'caffeine drink', 15, 51, 38);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (30, 'Clams', 'portion options: small or large', 1, 84, 30);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (31, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 8, 75, 65);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (32, 'Octopus', 'options: small or large', 4, 53, 40);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (33, 'Still water', 'refreshing drink', 5, 77, 33);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (34, 'Oatmeal cookies', 'dry food', 1, 2, 35);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (35, 'Still water', 'refreshing drink', 15, 44, 4);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (36, 'Instant coffee', 'caffeine drink', 7, 18, 38);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (37, 'Sparkling water', 'The water contains a lot of magnesium', 11, 82, 49);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (38, 'Octopus', 'options: small or large', 12, 46, 7);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (39, 'Clams', 'portion options: small or large', 3, 60, 93);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (40, 'Octopus', 'options: small or large', 11, 73, 47);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (41, 'Sparkling water', 'The water contains a lot of magnesium', 1, 81, 38);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (42, 'Clams', 'portion options: small or large', 3, 34, 15);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (43, 'Sparkling water', 'The water contains a lot of magnesium', 14, 91, 60);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (44, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 13, 46, 38);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (45, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 4, 29, 3);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (46, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 6, 49, 92);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (47, 'Instant coffee', 'caffeine drink', 1, 76, 35);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (48, 'Oatmeal cookies', 'dry food', 8, 4, 94);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (49, 'Sparkling water', 'The water contains a lot of magnesium', 1, 23, 81);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (50, 'Clams', 'portion options: small or large', 15, 56, 60);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (51, 'Oatmeal cookies', 'dry food', 8, 81, 100);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (52, 'Clams', 'portion options: small or large', 2, 27, 48);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (53, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 11, 54, 79);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (54, 'Octopus', 'options: small or large', 5, 80, 5);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (55, 'Oatmeal cookies', 'dry food', 8, 60, 74);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (56, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 7, 3, 26);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (57, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 4, 10, 89);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (58, 'Oatmeal cookies', 'dry food', 11, 15, 7);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (59, 'Clams', 'portion options: small or large', 3, 27, 20);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (60, 'Sparkling water', 'The water contains a lot of magnesium', 6, 78, 38);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (61, 'Sparkling water', 'The water contains a lot of magnesium', 12, 50, 71);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (62, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 12, 90, 75);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (63, 'Oatmeal cookies', 'dry food', 14, 82, 23);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (64, 'Still water', 'refreshing drink', 8, 37, 2);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (65, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 7, 28, 56);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (66, 'Clams', 'portion options: small or large', 13, 95, 44);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (67, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 5, 46, 86);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (68, 'Still water', 'refreshing drink', 6, 53, 82);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (69, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 10, 67, 31);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (70, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 3, 26, 53);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (71, 'Still water', 'refreshing drink', 5, 84, 77);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (72, 'Clams', 'portion options: small or large', 9, 81, 73);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (73, 'Still water', 'refreshing drink', 15, 12, 99);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (74, 'Clams', 'portion options: small or large', 11, 29, 42);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (75, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 2, 34, 4);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (76, 'Clams', 'portion options: small or large', 10, 49, 96);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (77, 'Instant coffee', 'caffeine drink', 13, 11, 58);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (78, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 4, 16, 87);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (79, 'Octopus', 'options: small or large', 4, 44, 7);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (80, 'Clams', 'portion options: small or large', 6, 98, 68);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (81, 'Instant coffee', 'caffeine drink', 14, 30, 77);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (82, 'Octopus', 'options: small or large', 15, 44, 35);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (83, 'Ham and cheese sandwich with seaweed', 'best sandwich in town', 10, 40, 99);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (84, 'Clams', 'portion options: small or large', 11, 41, 45);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (85, 'Oatmeal cookies', 'dry food', 11, 30, 87);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (86, 'Sparkling water', 'The water contains a lot of magnesium', 1, 36, 44);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (87, 'Clams', 'portion options: small or large', 6, 52, 67);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (88, 'Still water', 'refreshing drink', 13, 40, 46);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (89, 'Instant coffee', 'caffeine drink', 1, 30, 26);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (90, 'Instant coffee', 'caffeine drink', 4, 12, 91);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (91, 'Oatmeal cookies', 'dry food', 2, 40, 83);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (92, 'Octopus', 'options: small or large', 10, 94, 92);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (93, 'Clams', 'portion options: small or large', 11, 44, 8);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (94, 'Oatmeal cookies', 'dry food', 1, 62, 94);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (95, 'Sparkling water', 'The water contains a lot of magnesium', 10, 21, 46);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (96, 'Octopus', 'options: small or large', 9, 56, 73);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (97, 'Oatmeal cookies', 'dry food', 2, 36, 89);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (98, 'Still water', 'refreshing drink', 13, 58, 2);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (99, 'Octopus', 'options: small or large', 7, 97, 20);
insert into MenuItems (ItemID, ItemName, ItemDescription, ItemPrice, MenuID, SeaFoodID) values (100, 'Instant coffee', 'caffeine drink', 14, 11, 90);
