insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (1, true, false, false,'2017-02-06');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (2, false, true, false, '2017-05-18');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (3, true, false, false, '2018-11-13');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (4, false, false, true, '2017-03-09');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (5, false, true, false, '2017-08-25');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (6, false, false, true, '2018-01-31');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (7, true, false, false,'2018-02-04');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (8, true, false, false, '2020-01-12');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (9, false, true, false, '2017-10-16');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (10, true, false, false, '2018-07-10');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (11, false, true, false, '2019-06-02');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (12, false, false, true, '2017-08-21');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (13, true, false, false, '2018-12-24');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (14, true, false, false, '2018-11-30');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (15, true, false, false, '2019-10-02');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (16, true, false, false, '2017-08-08');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (17, true, false, false,'2017-08-10');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (18, false, false, true, '2017-07-29');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (19, true, false, false, '2018-10-22');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (20, true, false, false,'2018-05-04');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (21, true, false, false,'2017-12-18');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (22, true, false, false, '2020-01-12');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (23, false, false, true, '2019-10-22');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (24, false, false, true, '2019-05-22');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (25, true, false, false, '2018-04-24');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (26, true, false, false,'2017-02-08');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (27, true, false, false, '2017-10-24');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (28, true, false, false,'2017-07-06');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (29, true, false, false, '2018-10-24');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (30, true, false, false, '2019-08-16');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (31, false, false, true, '2018-11-29');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (32, true, false, false, '2018-03-01');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (33, false, false, true, '2017-12-05');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (34, false, false, true, '2019-04-23');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (35, false, false, true, '2018-01-07');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (36, true, false, false, '2019-06-15');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (37, true, false, false, '2018-02-23');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (38, false, false, true, '2018-01-08');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (39, true, false, false, '2018-07-12');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (40, true, false, false, '2017-07-15');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (41, true, false, false, '2018-11-08');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (42, true, false, false,'2018-06-30');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (43, true, false, false,'2017-02-14');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (44, true, false, false,'2017-11-25');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (45, false, true, false, '2017-08-02');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (46, false, true, false, '2019-09-02');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (47, true, false, false, '2017-10-08');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (48, true, false, false, '2018-05-07');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (49, true, false, false, '2018-05-20');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (50, true, false, false,'2017-06-15');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (51, false, false, true, '2017-02-28');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (52, false, true, false, '2017-10-25');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (53, true, false, false,'2018-09-04');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (54, true, false, false, '2018-04-23');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (55, false, true, false, '2019-11-16');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (56, false, false, true, '2019-04-23');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (57, true, false, false, '2017-02-12');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (58, true, false, false, '2017-02-14');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (59, true, false, false,'2018-01-07');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (60, true, false, false, '2018-12-16');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (61, true, false, false,'2017-08-23');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (62, false, false, true, '2019-05-21');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (63, false, true, false, '2019-05-17');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (64, true, false, false, '2017-11-28');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (65, true, false, false, '2017-12-23');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (66, true, false, false, '2019-01-11');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (67, true, false, false, '2017-08-21');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (68, true, false, false, '2017-07-24');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (69, false, false, true, '2017-06-18');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (70, true, false, false, '2018-10-13');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (71, true, false, false, '2018-07-08');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (72, true, false, false, '2018-01-08');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (73, false, true, false, '2017-08-10');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (74, true, false, false, '2019-08-06');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (75, false, true, false, '2017-10-09');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (76, true, false, false, '2017-03-16');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (77, false, true, false, '2018-07-06');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (78, false, true, false, '2019-12-03');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (79, false, true, false, '2019-02-03');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (80, true, false, false, '2018-02-14');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (81, false, false, true, '2018-10-19');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (82, false, true, false, '2019-10-19');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (83, true, false, false, '2018-11-26');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (84, true, false, false, '2017-10-25');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (85, true, false, false, '2018-10-26');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (86, true, false, false, '2019-07-24');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (87, false, true, false, '2019-07-24');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (88, false, true, false, '2019-08-11');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (89, true, false, false, '2019-12-01');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (90, false, true, false, '2019-07-23');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (91, false, true, false, '2017-12-29');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (92, false, false, true, '2017-11-02');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (93, false, false, true, '2019-01-13');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (94, true, false, false,'2017-02-15');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (95, true, false, false, '2019-12-18');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (96, true, false, false, '2019-06-11');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (97, false, false, true, '2018-04-25');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (98, true, false, false, '2018-09-11');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (99, true, false, false, '2018-01-19');
insert into Payments (PaymentID, CashPaymnet, BankTransferPaymnet, CardPayment, PaymentDate) values (100, true, false, false,'2017-01-26');
